name: SparkPythonDeequ
description: ''
version: '1.0'
author: nathan+demo@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: sparkpythondeequ
  parentArtefactID: devteam
  buildSystem: wheel
  author: null
  createdAt: '2024-03-08 21:12:31'
pipelines:
  pipelines/Sample_Pipeline:
    name: Sample_Pipeline
    description: ''
    author: nathan+demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-08 21:12:31'
    datasets:
      inputs: []
      outputs:
      - datasets/dq_failure_output
      - datasets/dq_verified_output
    subgraphs: []
    dependencies: {}
datasets:
  datasets/dq_failure_output:
    name: dq_failure_output
    description: ''
    author: nathan+demo@prophecy.io
    createdAt: '2024-03-11 03:36:57'
    mode: batch
    physicalDatasets:
      DBX_Dev:
        fabricId: 4345
        datasetType: Database
        description: ''
        author: nathan+demo@prophecy.io
        createdAt: '2024-03-11 03:36:57'
  datasets/dq_verified_output:
    name: dq_verified_output
    description: ''
    author: nathan+demo@prophecy.io
    createdAt: '2024-03-11 03:38:01'
    mode: batch
    physicalDatasets:
      DBX_Dev:
        fabricId: 4345
        datasetType: Database
        description: ''
        author: nathan+demo@prophecy.io
        createdAt: '2024-03-11 03:38:01'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/Deequ:
      name: Deequ
      category: Transform
      subCategory: ''
      description: null
      author: nathan+demo@prophecy.io
      mode: batch
      files:
      - devteam_sparkpythondeequ/gems/Deequ.py
      gemType: ComponentGem
      dependencies: []
      createdAt: '2024-03-11 03:30:13'
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-08 21:12:31'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-03-08 21:11:00'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.4
    isDefault: true
    author: null
    createdAt: '2024-03-08 21:11:00'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
